name: Trigger auto deployment for paranoidcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/paranoidcontainerapp-AutoDeployTrigger-1518e6cd-8615-4049-8625-f2fd35c6f9d4.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PARANOIDCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: paranoidandroid.azurecr.io
          registryUsername: ${{ secrets.PARANOIDCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PARANOIDCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: paranoidcontainerapp
          resourceGroup: DiscordGroupNO
          imageToBuild: paranoidandroid.azurecr.io/paranoidcontainerapp:${{ github.sha }}
          

     

